/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ChatView: typeof import('./src/components/ChatView.vue')['default']
    MessageInput: typeof import('./src/components/MessageInput.vue')['default']
    MessageItem: typeof import('./src/components/MessageItem.vue')['default']
    MessageList: typeof import('./src/components/MessageList.vue')['default']
    PermissionDialog: typeof import('./src/components/PermissionDialog.vue')['default']
    StatusBar: typeof import('./src/components/StatusBar.vue')['default']
  }
}
